/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        ibm: {
          foreground: "#31353f",
          background: "#f4f5f4",
        },
      },
      fontFamily: {
        commitmono: [
          "CommitMono",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      typography: ({ theme }) => ({
        ibm: {
          css: {
            "--tw-prose-body": theme("colors.ibm.foreground"),
            "--tw-prose-headings": theme("colors.ibm.foreground"),
            "--tw-prose-lead": theme("colors.ibm.foreground"),
            "--tw-prose-links": theme("colors.ibm.foreground"),
            "--tw-prose-bold": theme("colors.ibm.foreground"),
            "--tw-prose-counters": theme("colors.ibm.foreground"),
            "--tw-prose-bullets": theme("colors.ibm.foreground"),
            "--tw-prose-hr": theme("colors.ibm.foreground"),
            "--tw-prose-quotes": theme("colors.ibm.foreground"),
            "--tw-prose-quote-borders": theme("colors.ibm.foreground"),
            "--tw-prose-captions": theme("colors.ibm.foreground"),
            "--tw-prose-code": theme("colors.ibm.foreground"),
            "--tw-prose-pre-code": theme("colors.ibm.background"),
            "--tw-prose-pre-bg": theme("colors.ibm.foreground"),
            "--tw-prose-th-borders": theme("colors.ibm.foreground"),
            "--tw-prose-td-borders": theme("colors.ibm.foreground"),
            "--tw-prose-invert-body": theme("colors.ibm.background"),
            "--tw-prose-invert-headings": theme("colors.ibm.background"),
            "--tw-prose-invert-lead": theme("colors.ibm.background"),
            "--tw-prose-invert-links": theme("colors.ibm.background"),
            "--tw-prose-invert-bold": theme("colors.ibm.background"),
            "--tw-prose-invert-counters": theme("colors.ibm.background"),
            "--tw-prose-invert-bullets": theme("colors.ibm.background"),
            "--tw-prose-invert-hr": theme("colors.ibm.background"),
            "--tw-prose-invert-quotes": theme("colors.ibm.background"),
            "--tw-prose-invert-quote-borders": theme("colors.ibm.background"),
            "--tw-prose-invert-captions": theme("colors.ibm.background"),
            "--tw-prose-invert-code": theme("colors.ibm.background"),
            "--tw-prose-invert-pre-code": theme("colors.ibm.background"),
            "--tw-prose-invert-pre-bg": theme("colors.ibm.background"),
            "--tw-prose-invert-th-borders": theme("colors.ibm.background"),
            "--tw-prose-invert-td-borders": theme("colors.ibm.background"),
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
