export const SITE_ID = "REDRNHLE";

export const GOALS = {
  DOWNLOAD_RESUME: "C8Z7PGH7",
  CLICK_SOCIAL_INSTAGRAM: "O2KPUELC",
  CLICK_SOCIAL_TWITTER: "S0DLXEEV",
  CLICK_SOCIAL_GITHUB: "PDFTCSJU",
};
