export const SITE_ID = "KHPSHQVW";

export const GOALS = {
  DOWNLOAD_RESUME: "F7DGJWQW",
  CLICK_SOCIAL_INSTAGRAM: "HFCLQZEW",
  CLICK_SOCIAL_TWITTER: "XDBZWJ0N",
  CLICK_SOCIAL_GITHUB: "KAMNBJCL"
};
